language: cpp

before_install:
  # installing dependencies
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-all-dev libiomp-dev zip unzip
  # snap
  - cd ..
  - wget "http://snap.stanford.edu/releases/Snap-4.0.zip"  
  - unzip Snap-4.0.zip -d snap_raw
  - mkdir snap
  - cp -r snap_raw/Snap-4.0/* snap
  - cd snap
  - make
  - cd ..
  - cd gluesless

script: make
