# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'

addons:
  apt:
    packages:
    - valgrind
    - libboost-all-dev
    - libudunits2-dev
    - gdal-bin
    - proj-bin

warnings_are_errors: true

r_packages:
  - covr

after_success:
  - CODECOV_TOKEN='c554b444-4c92-476c-a383-7fc5a755e398' Rscript -e 'library(covr); codecov()'